### ISSUE TITLE
iris killer

### ISSUE THREAD

**Issue by oddrobbia** [MineDragonCZ/Aunis1#59]
so the idea was good you die in the entering side of the stargate if there is an iris at the other side the bad side of this the gate not shut down until someone go in and if the gate have infinite energy and you teleport back to your grave on the server for example you die instant because the grave in the event horizon because the eventhorizon is not a block like the vanila portals to prevent the grave spawn inside the open stargate

**Comment by catalyticenzyme** [comment]
Assuming I'm understanding this correctly because I'm having a little trouble reading it—that is, assuming that what you're saying is that if you gate to somewhere with an iris, die, and then use something that teleports you to your grave, you sometimes teleport into the still-open gate and die again—this is already an issue with the idea of teleporting you to your grave; people who fall into the lava ocean in the Nether have the very same problem and must do a tricky dance to retrieve their items (namely, draining the nearby lava) just like someone who dies in a Stargate has to do a tricky dance to retrieve their items (namely, disengaging the gate).

**Comment by oddrobbia** [comment]
yeah because they forgot to add the thing to the stargate if no one enters its needs to be shut down beacuse its have infinite energy until and admin gets online it will be active and nobody can shut it down because no other way to go to the nether then that stargate

**Comment by matousss** [comment]
I don't care you teleport into opened gate. The gate should stay opened because by cannon it can be opened if you have huge amount of energy running into stargate. I will propably add some rule which would extremely increase powerdraw after normal gate cycle time ran out.
